# Generated by Django 3.0.2 on 2020-02-08 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_auto_20200208_1559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
