# Generated by Django 3.0.7 on 2020-07-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_blog_articles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_articles',
            name='Status',
            field=models.CharField(choices=[('A', 'Approved')], max_length=1),
        ),
    ]
