# Generated by Django 3.0 on 2020-07-05 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0003_auto_20200703_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reply',
            new_name='parent',
        ),
    ]
