# Generated by Django 3.0.7 on 2020-06-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
