# Generated by Django 3.0 on 2020-07-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200630_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user_model',
            name='Age',
            field=models.IntegerField(null=True),
        ),
    ]
